name: .NET NuGet package push

on:
  workflow_run:
    workflows:
      - .NET Continuous Integration
    types:
      - completed
    branches:
      - releases/**

jobs:
  github_packages:
    name: Publish to GitHub packages
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .NET NuGet Push action
        uses: thnetii/gh-actions/def/typescript-action-prepare@main
        with:
          action-name: dotnet-nuget-push
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.repository.owner.login }}-${{ github.event.workflow_run.repository.name }}-nupkg-release
          repo: ${{ github.repository }}
          path: artifacts
      - name: dotnet nuget push
        uses: thnetii/gh-actions/def/dotnet-nuget-push@main
        with:
          path: artifacts/**/*.nupkg
          skip-duplicate: true
  azure_devops_packaging:
    name: Publish to Azure DevOps artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .NET NuGet Push action
        uses: thnetii/gh-actions/def/typescript-action-prepare@main
        with:
          action-name: dotnet-nuget-push
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.repository.owner.login }}-${{ github.event.workflow_run.repository.name }}-nupkg-release
          repo: ${{ github.repository }}
          path: artifacts
      - name: dotnet nuget push
        uses: thnetii/gh-actions/def/dotnet-nuget-push@main
        with:
          path: artifacts/**/*.nupkg
          source: https://x-access-token:${{ secrets.AZURE_DEVOPS_PACKAGING_READWRITE_ACCESS_TOKEN }}@pkgs.dev.azure.com/thnetii/artifacts/_packaging/public/nuget/v3/index.json
          api-key: ${{ github.sha }}
          skip-duplicate: true
