name: .NET NuGet package push

on:
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - .NET Continuous Integration
    types:
      - completed
    branches:
      - releases/**

jobs:
  github_packages:
    name: Publish to GitHub packages
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .NET NuGet Push action
        uses: thnetii/gh-actions/typescript-action-prepare@main
        with:
          action-name: dotnet-nuget-push
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.repository.owner.login }}-${{ github.event.workflow_run.repository.name }}-nupkg-release
          repo: ${{ github.repository }}
          path: artifacts
      - name: dotnet nuget push
        uses: thnetii/gh-actions/dotnet-nuget-push@main
        with:
          path: artifacts/**/*.nupkg
          skip-duplicate: true
  azure_devops_packaging:
    name: Publish to Azure DevOps artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Prepare .NET NuGet Push action
        uses: thnetii/gh-actions/typescript-action-prepare@main
        with:
          action-name: dotnet-nuget-push
      - name: dotnet nuget add source azure-devops
        shell: bash
        run: dotnet nuget add source https://pkgs.dev.azure.com/thnetii/_packaging/public/nuget/v3/index.json --name azure-devops --username x-access-token --password ${{ secrets.AZURE_DEVOPS_PACKAGING_READWRITE_ACCESS_TOKEN }} --valid-authentication-types basic --store-password-in-clear-text
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token }}
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ github.event.workflow_run.repository.owner.login }}-${{ github.event.workflow_run.repository.name }}-nupkg-release
          repo: ${{ github.repository }}
          path: artifacts
      - name: dotnet nuget push
        uses: thnetii/gh-actions/dotnet-nuget-push@main
        with:
          path: artifacts/**/*.nupkg
          source: azure-devops
          api-key: ${{ github.sha }}
          skip-duplicate: true
      - name: dotnet nuget remove source azure-devops
        if: ${{ always() }}
        shell: bash
        run: dotnet nuget remove source azure-devops
