name: .NET NuGet package test

on:
  workflow_dispatch: {}
  workflow_run:
    workflows:
      - .NET NuGet package push
    types:
      - completed

jobs:
  nupkg_usage_test:
    name: Test published nupkg (${{ matrix.display }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source:
          - github
          - azuredevops
        include:
          - source: github
            display: GitHub Packages
            nuget-configuration: |
              <?xml version="1.0" encoding="utf-8"?>
              <configuration>
                <packageSources>
                  <add key="github" value="https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" />
                </packageSources>
                <packageSourceCredentials>
                  <github>
                    <add key="username" value="github-actions" />
                    <add key="cleartextpassword" value="" />
                    <add key="validauthenticationtypes" value="basic" />
                  </github>
                </packageSourceCredentials>
              </configuration>
          - source: azuredevops
            display: Azure DevOps
            nuget-configuration: |
              <?xml version="1.0" encoding="utf-8"?>
              <configuration>
                <packageSources>
                  <add key="azuredevops" value="https://pkgs.dev.azure.com/thnetii/_packaging/public/nuget/v3/index.json" />
                </packageSources>
              </configuration>
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: 'Overwrite NuGet configuration'
        shell: pwsh
        run: |
          [string]$NugetConfig = $ENV:MATRIX_NUGET_CONFIG_CONTENT
          $NugetConfig | Out-File ./nuget.config -Encoding utf8 -Force
        env:
          MATRIX_NUGET_CONFIG_CONTENT: ${{ matrix['nuget-configuration'] }}
        working-directory: test
      - name: 'Add GitHub Access Token to NuGet configuration'
        if: matrix['source'] == 'github'
        shell: pwsh
        run: |
          [xml]$NugetConfig = Get-Content ./nuget.config
          $PasswordNode = $NugetConfig.SelectSingleNode("/configuration/packageSourceCredentials/github/add[@key=`"cleartextpassword`"]")
          $PasswordNode.SetAttribute("value", "${{ github.token }}")
          $NugetConfig.Save((Resolve-Path ./nuget.config))
        working-directory: test
      - name: 'Run .NET SDK'
        shell: pwsh
        run: |
          dotnet add package --prerelease THNETII.RepositoryDefault.Dotnet.Build.GitHub
          dotnet build -bl:../MSBuild.Build.binlog -property:BuildId=${{ github.run_number }} -property:BuildSourceBranch=${{ github.ref }} -consoleLoggerParameters:NoSummary
          dotnet pack -bl:../MSBuild.Pack.binlog -property:BuildId=${{ github.run_number }} -property:BuildSourceBranch=${{ github.ref }} -consoleLoggerParameters:NoSummary
          Remove-Item -Force ../nuget.config
        working-directory: test/THNETII.RepositoryDefault.Dotnet.Build.Test
      - name: 'Upload test directory as artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-test-${{ matrix.source }}
          path: test
  restore_additional_sources_test:
    needs:
      - nupkg_usage_test
    name: Test RestoreAdditionalProjectSources property
    runs-on: ubuntu-latest
    steps:
      - name: Chekout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: 'Overwrite NuGet configuration'
        shell: pwsh
        run: |
          Remove-Item -Force ./nuget.config

          $DirectoryBuildPropsFilePath = Resolve-Path ./Directory.Build.props
          [xml]$DirectoryBuildProps = Get-Content -LiteralPath $DirectoryBuildPropsFilePath
          $ProjectElem = $DirectoryBuildProps.SelectSingleNode("/Project")
          $PropGroup = $DirectoryBuildProps.CreateElement("PropertyGroup")
          $PropElem = $DirectoryBuildProps.CreateElement("RestoreAdditionalProjectSources")
          [string]$PropValueText = "`$(RestoreAdditionalProjectSources);"
          $PropValueText += "https://pkgs.dev.azure.com/thnetii/_packaging/public/nuget/v3/index.json"
          $PropValue = $DirectoryBuildProps.CreateTextNode($PropValueText)
          $PropElem.AppendChild($PropValue) | Out-Null
          $PropGroup.AppendChild($PropElem) | Out-Null
          $ProjectElem.AppendChild($PropGroup) | Out-Null
          $DirectoryBuildProps.Save($DirectoryBuildPropsFilePath)
        working-directory: test
      - name: 'Run .NET SDK'
        shell: pwsh
        run: |
          dotnet add package --prerelease THNETII.RepositoryDefault.Dotnet.Build.GitHub
          dotnet build -bl:../MSBuild.Build.binlog -property:BuildId=${{ github.run_number }} -property:BuildSourceBranch=${{ github.ref }} -consoleLoggerParameters:NoSummary
          dotnet pack -bl:../MSBuild.Pack.binlog -property:BuildId=${{ github.run_number }} -property:BuildSourceBranch=${{ github.ref }} -consoleLoggerParameters:NoSummary
        working-directory: test/THNETII.RepositoryDefault.Dotnet.Build.Test
      - name: 'Upload test directory as artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-test-restoreadditionalprojectsources
          path: test
